---
- name: POC mediawiki server
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3

  #
  tasks:
  - name: Install packages
    shell: |
      dnf module reset php
      dnf module enable php:7.4 -y
      dnf install httpd php php-mysqlnd php-gd php-xml mariadb-server mariadb php-mbstring php-json mod_ssl php-intl php-apcu wget -y 
    register: packages
  - debug: var=packages.stdout_lines

  - name: Start mariadb service
    service:
      name: mariadb
      state: started
      enabled: yes

  - name: Create user, grant privilage in DB
    shell: |
       mysql -u root -e "CREATE USER 'wiki'@'localhost' IDENTIFIED BY 'THISpasswordSHOULDbeCHANGED';"
       mysql -u root -e "CREATE DATABASE wikidatabase;"
       mysql -u root -e "GRANT ALL PRIVILEGES ON wikidatabase.* TO 'wiki'@'localhost';"
       mysql -u root -e "FLUSH PRIVILEGES;"
       mysql -u root -e "show databases;"
    ignore_errors: yes
    register: db
  - debug: var=db.stdout_lines

  - name: Download mediawiki
    get_url:
       url: https://releases.wikimedia.org/mediawiki/1.38/mediawiki-1.38.1.tar.gz
       dest: /tmp

  - name: create code directory
    file:
      dest: /opt/code
      state: directory

  - name: untar the mediawiki
    unarchive:
       src: /tmp/mediawiki-1.38.1.tar.gz
       dest: /opt/code
       remote_src: yes

  - name: Create symbolic link 
    file:
      src: "/opt/code/mediawiki-1.38.1/"
      dest: /var/www/mediawiki
      state: link

  - name: Change ownership
    shell: chown -v -R apache:apache /var/www/mediawiki
    register: chown
  - debug:
      var: chown.stdout_lines

  - name: post-install configuration
    replace:
      path: /etc/httpd/conf/httpd.conf
      regexp: 'DocumentRoot "/var/www/html"'
      replace: 'DocumentRoot "/var/www/"'

  - name: selinux policy over the directory
    shell: |
      setenforce 0
      restorecon -FR /var/www/mediawiki

  - name: restart httd service
    shell: service httpd restart

