
---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  #
  tasks:
  - name: Download mediawiki tar file from url
    get_url:
       url: "{{ version }}"
       dest: /tmp

  - name: Remove the code directory incase previous code might exist
    file:
       path: /opt/code
       state: absent

  - name: Create new code directory
    file:
      dest: /opt/code
      state: directory

  - name: Find downloaded mediawiki package
    find: 
      paths: /tmp 
      patterns: "mediawiki-*.tar.gz"
    register: find_result

  - name: Untar the downloaded mediawiki code
    unarchive:
       src: "{{ item.path }}"
       dest: /opt/code
       remote_src: yes
    with_items: "{{ find_result.files }}"

  - name: Remove previous code mediawiki symlink
    file:
      path: "/var/www/mediawiki"
      state: absent

  - name: Create new code symbolic link 
    shell: |
       cd /var/www/
       ln -s /opt/code/mediawiki-*/ mediawiki

  - name: Change ownership of the new code
    shell: chown -v -R apache:apache /var/www/mediawiki
    register: chown
  - debug:
      var: chown.stdout_lines

  - name: Restart httpd service
    shell: service httpd restart








