name: Create mediawiki environment using terraform

on:
  push:
    branches:
      - master

jobs:
  build:
    name: hosting application
    runs-on: [self-hosted, linux, x64]
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1
