name: POC mediawiki environment using terraform & ansible

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
 # push:
 #   branches: [ "main" ]
 # pull_request:
 #   branches: [ "main" ]

  workflow_dispatch:
    inputs:
      action:
        description: 'terraform action: apply or destroy'
        default: 'destroy'
        required: false
        type: string

jobs:
  build:
    name: hosting application
    runs-on: [self-hosted, linux, x64]
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1
      
    - name: Terraform validate
      run: |
        cd terraform
        terraform init
        terraform ${{ inputs.action }}
        
    - name: Terraform ${{ inputs.action }}
      run: |
        cd terraform
        
  #      terraform apply --auto-approve
  #      terraform destroy --auto-approve
