name: POC mediawiki environment using terraform & ansible

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
 # push:
 #   branches: [ "main" ]
 # pull_request:
 #   branches: [ "main" ]

  workflow_dispatch:
    inputs:
      action:
        description: 'terraform action: apply or destroy'
        default: 'destroy'
        required: false
        type: string

jobs:
  build:
    name: hosting application
    runs-on: [self-hosted, linux, x64]
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1
      
    - name: create a custom workspace
      run: |
       mkdir /opt/custom_workspace/project_mediawiki || true
       cp terraform/*.tf /opt/custom_workspace/project_mediawiki
       ls -lthra /opt/custom_workspace/project_mediawiki/*
      
    - name: Terraform validate
      run: |
        cd /opt/custom_workspace/project_mediawiki
        terraform init
        terraform validate
        
    - name: Terraform ${{ inputs.action }}
      run: |
        cd /opt/custom_workspace/project_mediawiki
        ls -lthra 
        
  #      terraform apply --auto-approve
  #      terraform destroy --auto-approve
