name: POC mediawiki environment using terraform & ansible

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
 # push:
 #   branches: [ "main" ]
 # pull_request:
 #   branches: [ "main" ]

  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'terraform action: apply or destroy'     
        required: true
        default: 'destroy' 
        type: choice
        options:
        - apply
        - destroy

jobs:
  build:
    name: hosting application
    runs-on: [self-hosted, linux, x64]
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

      # already created "/opt/custom_workspace" on runner server
    - name: create a custom workspace
      run: |
       mkdir /opt/custom_workspace/project_mediawiki || true
       mkdir /opt/custom_workspace/project_mediawiki/terraform || true
       cp terraform/*.tf /opt/custom_workspace/project_mediawiki/terraform
       ls -lthra /opt/custom_workspace/project_mediawiki/*
      
    - name: Terraform validate
      run: |
        cd /opt/custom_workspace/project_mediawiki
        terraform init
        terraform validate
        
    - name: Terraform ${{ inputs.terraform_action }}
      run: |
        cd /opt/custom_workspace/project_mediawiki/terraform
        ls -lthra 
        terraform ${{ inputs.terraform_action }} --auto-approve
  
